# SPDX-License-Identifier: MIT-0
---
# vars file for oc-mirror
openshift_version: 4.22.4
oc_mirror_workdir: /opt/oc-mirror
oc_mirror_archive_path: /var/tmp/oc-mirror.tar.gz
quay_workdir: /opt/quay-mirror
