---
######################################################
# ansible-playbook playbooks/prereqs.yaml \
#   -i inventory.yaml \
######################################################
- name: Install prerequisites
  hosts: localhost
  become: true
  gather_facts: true
  tasks:
    - name: Install required packages
      ansible.builtin.package:
        name:
          - python-pip3
    - name: Install required Python packages
      ansible.builtin.pip:
        name:
          - netaddr
          - jmespath
